version: '3.1'

services:
  api-gateway:
    container_name: api-gateway
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./api_gateway/nginx:/etc/nginx
    depends_on:
      - item_service

  item_service:
    image: item_service
    container_name: item_service
    build:
      context: item_service
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ENVIRONMENT: development
      MONGODB: mongodb://mongodb:27017
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongosh mongodb:27017/test --quiet"
      interval: 30s
      timeout: 10s
      retries: 100
      start_period: 10s
      start_interval: 5s
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: